#spring.application.name=springbootwebapplication
#spring.h2.console.enabled=true
#
#spring.datasource.url=jdbc:h2:file:F:/New Folder/SpringBootWebTutorial_DB/DB
#spring.datasource.username=shwetaDB
#spring.datasource.password=Shweta123


spring.application.name=springbootwebapplication

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:file:F:/New Folder/SpringBootWebTutorial_DB/DB
spring.datasource.username=shwetaDB
spring.datasource.password=Shweta123
spring.jpa.hibernate.ddl-auto=update